// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HasSelection: typeof import('./src/components/select/HasSelection.vue')['default']
    MainShow: typeof import('./src/components/logo/MainShow.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NotSelection: typeof import('./src/components/select/NotSelection.vue')['default']
    NResult: typeof import('naive-ui')['NResult']
    NSpin: typeof import('naive-ui')['NSpin']
    Process: typeof import('./src/pages/process.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
